import { fb } from "./fb"
import { post } from "./post"
let POST = new post()
let FB = new fb();
console.log(FB.likes)
console.log(FB.state)
console.log("POST", POST._postLikes)
console.log("###########################USER1 Likes")
FB.like(POST)
console.log(FB.likes)
console.log(FB.state)
console.log("POST", POST._postLikes)
console.log("##########################USER1 Dislikes")
FB.like(POST)
console.log(FB.likes)
console.log(FB.state)
console.log("POST", POST._postLikes)
console.log("#########################USER1 Likes")
FB.like(POST)
console.log(FB.likes)
console.log(FB.state)
console.log("POST", POST._postLikes)


// new user
let newFB = new fb()
console.log("newFB", newFB.likes)
console.log("newFB", newFB.state)
console.log("newFBPOST", POST._postLikes)
console.log("########################USER2 Likes")
newFB.like(POST)
console.log("newFB", newFB.likes)
console.log("newFB", newFB.state)
console.log("newFBPOST", POST._postLikes)
console.log("######################USER2 DisLikes")
newFB.like(POST)
console.log("newFB", newFB.likes)
console.log("newFB", newFB.state)
console.log("newFBPOST", POST._postLikes)
console.log("########################USER2 Likes")
newFB.like(POST)
console.log("newFB", newFB.likes)
console.log("newFB", newFB.state)
console.log("newFBPOST", POST._postLikes)

