"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var fb_1 = require("./fb");
var post_1 = require("./post");
var POST = new post_1.post();
var FB = new fb_1.fb();
console.log(FB.likes);
console.log(FB.state);
console.log("POST", POST._postLikes);
console.log("###########################USER1 Likes");
FB.like(POST);
console.log(FB.likes);
console.log(FB.state);
console.log("POST", POST._postLikes);
console.log("##########################USER1 Dislikes");
FB.like(POST);
console.log(FB.likes);
console.log(FB.state);
console.log("POST", POST._postLikes);
console.log("#########################USER1 Likes");
FB.like(POST);
console.log(FB.likes);
console.log(FB.state);
console.log("POST", POST._postLikes);
// new user
var newFB = new fb_1.fb();
console.log("newFB", newFB.likes);
console.log("newFB", newFB.state);
console.log("newFBPOST", POST._postLikes);
console.log("########################USER2 Likes");
newFB.like(POST);
console.log("newFB", newFB.likes);
console.log("newFB", newFB.state);
console.log("newFBPOST", POST._postLikes);
console.log("######################USER2 DisLikes");
newFB.like(POST);
console.log("newFB", newFB.likes);
console.log("newFB", newFB.state);
console.log("newFBPOST", POST._postLikes);
console.log("########################USER2 Likes");
newFB.like(POST);
console.log("newFB", newFB.likes);
console.log("newFB", newFB.state);
console.log("newFBPOST", POST._postLikes);
